### ISSUE TITLE
trouble with daemonize

### ISSUE THREAD

**Issue by pricejh** [dex4er/Starlight#3]
Thanks for all your work on this!   On a CentOS 7.4 box running Perl 5.16.3

plackup -s Starlight --daemonize 

results in error "Failed to load resource: The network connection was lost" upon first access. Under the same conditions --

plackup -s Starlight
works as expected.

I would offer more information if I knew what might be helpful.  Please advise.

**Comment by dex4er** [comment]
Can't reproduce it on Debian and with the latest CPAN libraries (Plack and others). 

Do you have the same with

`starlight --daemonize` command?

Can you use `--error-log` option for `starlight` or `plackup` command and see what happened?

```
  --error-log:
    Specify the pathname of a file where the error log should be written.
    This enables you to still have access to the errors when using
    "--daemonize". (default: none)
```
